language: java
jdk:
- oraclejdk8
os:
- linux
sudo: false

cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master

after_success:
- mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: bash ./ci/deploy.sh

env:
  global:
  - secure: oeiMQDgSwqQSZez1apJ2jQ8LnD6EdLL1db+ICx/UnaLY736urN2AD6OUfHZiELmxgtVVSdy0Ei+NBHRYUKb5RTZDgm02kjMzGv6GVQp8bYlA0HjEmD2gXayQxj8uNBpCAO0QQyipgBsF5kVYCUoHKmdds0UOv+wIB9JR/V1Hd1mU1T7Y5sfRxloE3UZlJkZn0Z00nGgeW72lVqqVKPDKeUnO56SNXWAnViiPfzdF/8qo2XDeQvW1mr/fG1h4HSWD3DVsl7ruVj3yhrwELsXGt5AvV1OWfHsCAcHtJq5Gyli493i3JNQj3bZnOb64Riqp4bUl8OKbMT122kiVYbyhefKnsBgCxOjdD4nzRF//Gsj2bkABCB/IUrsuTTUZU3LU0CTqAEuwF6qxvJKexAt8JMHLPE0U+nTNoStljCqlxiMBu88eLpOxV1FPX0ssTbgyCm4O4VMEJSgWCMC2Ki4PnsI/GVBvdPfVZ8JpyL6kBktut1hmFvJLKTJO0ZrarTk09lMSBVnTJ5J7X7LL2VDcRx4iVch+sppLa12h5K5r6I/q6/i2JqTeXtTIlCWm5axBe540Upr/zqMn9V2cwbPdLup4GzbLdehkxvmrQd+GZ2k8Qfyt/W3zIDRga7ReyIe1bYLjGd7VrQXH6VnOLRYfhrwwTRBnO9P4wA981/Ba9yE=
  - secure: mLYDbgnxGMGX33dp4OgB+LW1cMRF3SpBdRF5c40ft9M2kzAEynBUNAMPJlG/uEPZz12Ej5ADitSj2Kfb/VMUoz2Vzw2esb8hJtDerekZdf0bPuB76azG+QgKYuvDfQ33nkBeRu5lk5sMKZy+GyP060cFVR5yp8Q73iVJUQ49KtvyzU4dHye/xXW33JLCjmNLewVKxoFd4l2YvwjD2cGjhx0pNZZVkFTK+1mMiR5bUk7Ya1RS098mNXm1x2XXVCzoedtEc9xi9/7tKlzgHzpcz1WpSve3y2Qw+35hJllF3vvCaFJjX8nd7zXojtOXy1QdtEZYfxknOmCjUNxsRaQSRQlXoXE0MMt/kQYeHU96PSQLO1wMJCdr47F894gLEfRF/h1KusoZk1PLpzDXXNbILxE4M54QxT642dIZXpZXJrIdAb6dZwMXdO9+H+DXP6mpbbCl+bkTICfEm3VuRdnylSxAAIzD7bwcsyxODgglgN2ONhz4fJxQm1DnrbJMMTHit2lsdZCFkRyzTnWrJ3QTz9ufKbxd+ItnWWmG+qF/tu0h+MXd+kfxchcFuq0RXmgzXpVqSp/B1b3w5KX3m0efKarPrLUWcvsv8ychgcSX+677Fu5JRqKVVXgvmajhrOkHLM30ZVT00NmZ59Pkdti4DYWwP8Euh7E1oVz29qGXoHI=
