language: java
jdk:
#  - openjdk7
  - oraclejdk8

sudo: false

# cache between builds
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

after_success:
  - mvn clean test jacoco:report coveralls:report