language: java

cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master

script:
  - mvn --batch-mode clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: bash ci/deploy.sh
