language: java
jdk:
- oraclejdk8
os:
- linux
sudo: false

cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master

after_success:
- mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: bash ./ci/deploy.sh

env:
  global:
  - secure: oeiMQDgSwqQSZez1apJ2jQ8LnD6EdLL1db+ICx/UnaLY736urN2AD6OUfHZiELmxgtVVSdy0Ei+NBHRYUKb5RTZDgm02kjMzGv6GVQp8bYlA0HjEmD2gXayQxj8uNBpCAO0QQyipgBsF5kVYCUoHKmdds0UOv+wIB9JR/V1Hd1mU1T7Y5sfRxloE3UZlJkZn0Z00nGgeW72lVqqVKPDKeUnO56SNXWAnViiPfzdF/8qo2XDeQvW1mr/fG1h4HSWD3DVsl7ruVj3yhrwELsXGt5AvV1OWfHsCAcHtJq5Gyli493i3JNQj3bZnOb64Riqp4bUl8OKbMT122kiVYbyhefKnsBgCxOjdD4nzRF//Gsj2bkABCB/IUrsuTTUZU3LU0CTqAEuwF6qxvJKexAt8JMHLPE0U+nTNoStljCqlxiMBu88eLpOxV1FPX0ssTbgyCm4O4VMEJSgWCMC2Ki4PnsI/GVBvdPfVZ8JpyL6kBktut1hmFvJLKTJO0ZrarTk09lMSBVnTJ5J7X7LL2VDcRx4iVch+sppLa12h5K5r6I/q6/i2JqTeXtTIlCWm5axBe540Upr/zqMn9V2cwbPdLup4GzbLdehkxvmrQd+GZ2k8Qfyt/W3zIDRga7ReyIe1bYLjGd7VrQXH6VnOLRYfhrwwTRBnO9P4wA981/Ba9yE=
  - secure: mLYDbgnxGMGX33dp4OgB+LW1cMRF3SpBdRF5c40ft9M2kzAEynBUNAMPJlG/uEPZz12Ej5ADitSj2Kfb/VMUoz2Vzw2esb8hJtDerekZdf0bPuB76azG+QgKYuvDfQ33nkBeRu5lk5sMKZy+GyP060cFVR5yp8Q73iVJUQ49KtvyzU4dHye/xXW33JLCjmNLewVKxoFd4l2YvwjD2cGjhx0pNZZVkFTK+1mMiR5bUk7Ya1RS098mNXm1x2XXVCzoedtEc9xi9/7tKlzgHzpcz1WpSve3y2Qw+35hJllF3vvCaFJjX8nd7zXojtOXy1QdtEZYfxknOmCjUNxsRaQSRQlXoXE0MMt/kQYeHU96PSQLO1wMJCdr47F894gLEfRF/h1KusoZk1PLpzDXXNbILxE4M54QxT642dIZXpZXJrIdAb6dZwMXdO9+H+DXP6mpbbCl+bkTICfEm3VuRdnylSxAAIzD7bwcsyxODgglgN2ONhz4fJxQm1DnrbJMMTHit2lsdZCFkRyzTnWrJ3QTz9ufKbxd+ItnWWmG+qF/tu0h+MXd+kfxchcFuq0RXmgzXpVqSp/B1b3w5KX3m0efKarPrLUWcvsv8ychgcSX+677Fu5JRqKVVXgvmajhrOkHLM30ZVT00NmZ59Pkdti4DYWwP8Euh7E1oVz29qGXoHI=
  - secure: HmvEblTdDHUncMowv2WSqYCFvymkal86g/xSbXVvZOKilddtm8uYo2BS+ovckyRHqlRKrpsdKd00PwvMWP84nXlhAKh7ObCEj4q9tQkkI3rkuT6Io4TDMKeI/BUUCyiTZeCn7Zvou0wBavRtA0upmAgn8aMRFGobSUspQeLdZ48bBwQNTQEHFT/yW4xYGXWnEHUf5FIKZnjKX4//DhD62YfeI74N/K9t5pGW1dXLMzu1Tm6eQyWn9Gle6h0zrybP8Cb98/4hj95xtWBXeYwTpzotyUaABErkJgg6SRaFNG3gqX/rYm1J/NeIiHXgKyNSFGT1EwQpDF7QDjJpkGNKDanMQ25PL7JpBDu00wSg/YAzLqSRtEybNmrdrQAOY6fwrMbGeGVZsO4Esjenq6ystbB25a/yvtPXnwokNxspER6+LUihs1LsOHTtWN7DyuryrzYOOjPh+xsQt0MlpcVFLrLW86Rzkb+0Tu0doIqAl95AdmwoBUe5hcrUoxLTbjp566gUm/mhnCcC1sDpt4BLZDn0mr7HE4bY4Xd23nz4xsYjymzQrXUt9UOoJuRc4JrIiMWTNQRwsyuwIUdFSNUHghnzpWcff9pJ7SFsXY1YMyqEHvJgfyH2q4F3z1555RdhH6ACBS2vQcTXYjCZFA0V9FAwaeWJ+xZ11HFpM9sD1PU=
  - secure: zMU+inaiPoYGcnEphIXkip4Y8Yr3QH6A5kG0y3HZXU7uC8hzBzE6iHajxY39kG0NYo89VRrTb8+4sslE/KIkIpyDgbHfqrtP+4OXcl8jVBwg0tgL1A3aJkFqXHqRCWYpgfnp7OZtL8vdSneD3UQ4dDUYkfutLsho5xhZQIW3JSvnyEUttupRIN6DTTUN7OKizBKXbPEYHqkZms5l+/4Uz2A7awKgZtXY8l4Pan0UKcA35HVyss7C5X7O0DnvHmD+3/YjeyKqYlsDfK3ZvpohRTvyQqcLGawbvTb77h95vLvVMXgIFGoCLFjiQ8fUO7WqaDX9bpjQaQq3zHMPpO3S4XMPneodfLr5uiT7zRv7oVSknheNZK/mmbLyzc8bVEZOaKbrMs3Qyz39lg8m8Vkwn8YiNu9vT5C/l6pQ6PesolGWw/iBbO3SI2kEH/SHCd3AjftOckrTLOz2I+TOgCXpQ0ZbxgWl8T07eXvpKnWKEB0O1YQmeGrzJXp5Ss8k8HoSmYMBkdO0OSuWQOO/8xTpL7vX0xTVlrouXSu3IV0+LjF8wNBESwaQdhijlq8AYVvm+8JZ5jU1NObKWzjdZ4xzwIZ5wyOnEb0lObr09T8ac445Bv8jbYqdREJnF/FdrOpX4etrTmlhbXxrkIu/moeFdnX/Wy/uPkkeJcL/85qNDcI=
